### ISSUE TITLE
IPCC authors with UK affiliations

### ISSUE THREAD

**Issue by RaoOfPhysics** [explorable-viz/fluid-examples#31]
Related to #20. All information is from publicly available sources (unless specified).

Key (‽):

* CLA: ??
* LA: ??
* RE: Reviewer ??

# AR6 WG1

_Sixth Assessment Report Working Group 1: The Physics Sciences Basis_

## Authors · [Source](https://apps.ipcc.ch/report/authors/report.authors.php?q=35&p=)

| Name | Affiliation | Chapter | Role |
|:-------|:-------|:-------|:-------|
| Edward Hawkins | National Centre for Atmospheric Science; University of Reading | Ch. 1 | LA |
| Gabriele C. Hegerl | University of Edinburgh (not from document) | Ch. 1 | RE |
| Shubha Sathyendranath | Plymouth Marine Laboratory | Ch. 2 | LA |
| Timothy Osborn | University of East Anglia | Ch. 2 | RE |
| Nicolas Bellouin | University of Reading | Ch. 3 |  LA |
| **Daniel Mitchell** | **University of Bristol** | Ch. 3 | RE |
| Christopher Jones | Met Office Hadley Centre | Ch. 4 | LA |
| Amanda Maycock | University of Leeds | Ch. 4 | LA |
| Peter M. Cox | University of Exeter | Ch. 5 | LA |
| Stephanie Henson | National Oceanographic Centre | Ch. 5 | LA |
| Nadine Unger | University of Exeter | Ch. 6 | LA |
| Piers Forster | University of Leeds | Ch. 7 | CLA |
| William Collins | University of Reading | Ch. 7 | LA |
| **Daniel Lunt** | **University of Bristol** | Ch. 7 | LA |
| **Matthew Palmer** | **University of Bristol**; Met office Hadley Centre | Ch. 7 | LA |
| Richard Allan | University of Reading | Ch. 8 | LA |
| Helene Hewitt (née Banks) | Met Office Hadley Centre | Ch. 9. | CLA |
| Tamsin Edwards | King's College London | Ch. 9 | LA |
| Andrew Turner | National Centre for Atmospheric Science; University of Reading | Ch. 10 | LA |
| Nigel Arnell | University of Reading | Ch. 12 | LA |
| Suraje Dessai | University of Leeds | Ch. 12 | LA |
| Richard Jones | Met Office Hadley Centre | Atlas | CLA |

## Contributors · [Source](https://www.ipcc.ch/report/ar6/wg1/downloads/report/IPCC_AR6_WGI_AnnexIX.pdf) [Bristol/Cambridge]

| Name | Affiliation |
|:-------|:-------|
| Paul T. Griffiths | University of Cambridge |
| Jonathan L. Bamber | University of Bristol |
| Joseph D. Daron | University of Bristol; Met Office Hadley Centre |
| Eunice Lo | University of Bristol |
| Daniela Schmidt | University of Bristol | 

# AR6 WG2

[…]

**Comment by rolyp** [comment]
More recent discussion on next IPCC cycle on Cabot mailing list (from Dann Mitchell, d.m.mitchell@bristol.ac.uk, presumably the Daniel Mitchell from the list above):

>Hi all – see e-mail below to nominate yourself for the next IPCC cycle. There is also a mailing list you can sign up to if you want to be notified about future involvement.
>
> It would be really good to get Bristol involvement in this – it does wonders for Bristol’s reputation (along with your own!). Following my last e-mail; Dani and I had a quick chat with Cabot about supporting applications, and managing expectations. We didn’t progress too much I’m afraid, but we are keen to help. My suggestion is that if you’d like to apply for this opportunity then let us know, and we can advise. Likewise with further IPCC cycles.
>
>Cheers,
>
>Dann
> 
>
> Professor Dann Mitchell (he/him)
> Met Office Joint Chair in Climate Hazards
> 
> University of Bristol
> Twitter: [@ClimateDann](https://twitter.com/ClimateDann) | Web: https://www.climatebristol.org/
>
>
>> Dear colleague,  
>>
>> I am writing to bring your attention to the Intergovernmental Panel for Climate Change’s (IPCC) call for the nomination of experts to draft the outline of the Working Group contributions to the Seventh Assessment Report (AR7) at a Scoping Meeting tentatively scheduled for December 2024.  
>>
>> The three Working Group contributions will cover the physical science basis of climate change, impacts, adaptation, and vulnerability to climate change, and the mitigation of climate change.
>>
>>The AR7 will also include an update of the 1994 Technical Guidelines for Assessing Climate Change Impacts and Adaptation in conjunction with the Working Group II contribution.  
>>
>> If you would like to be considered for nomination, please take the time to read the enclosed letter, which contains more information on the nomination process and how to apply as a UK expert.
>>
>>Please return your completed nomination form and CV to [ipccauthorsupportuk@energysecurity.gov.uk](mailto:ipccauthorsupportuk@energysecurity.gov.uk) with the subject line “AR7 nomination form”. We will be accepting applications until June 2nd, 23:59 BST. 
>>
>> If you would like to remain informed about future nomination calls and other opportunities to contribute to the IPCC, please complete this form to be added to our mailing list.  
>>
>> Please do forward this mail and the enclosed documents to any colleagues who may be interested in contributing to the AR7 scoping process. We look forward to receiving your nominations.   
>>
>> Kind regards,  
>> Nadya Rauch on behalf of Jolene Cook, UK IPCC Focal Point
