### ISSUE TITLE
Puppeteer-based article validation

### ISSUE THREAD

**Issue by rolyp** [explorable-viz/fluid-examples#52]
Very simple high-level test, using [Puppeteer](https://www.npmjs.com/package/puppeteer), which certifies that the artifact exists and is minimally reproducible. To become part of the template repo.

E.g.: check we can serve the web page on localhost, navigate to localhost, and then find the expected `svg` element on the web page).

**Comment by RaoOfPhysics** [comment]
Closed with https://github.com/explorable-viz/fluid-example-ipcc-ar6-01/commit/feace5512ea28f93301a02a93c6b4a0140b5febd
